Work on Travis-CI configuration

diff --git a/test/test_that_invalid_signature_returns_401 b/test/test_that_invalid_signature_returns_401
--- a/test/test_that_invalid_signature_returns_401
+++ b/test/test_that_invalid_signature_returns_401
@@ -3,7 +3,7 @@
 echo -n '{"client":"myTestClient","pwd":"v8(9D1A>7n9J<","scope":["test"],"rw":false,"exp":4405688331,"hawkAlgorithm":"sha256"}' | \
 	iron -i 1 -p $IRON_PASSWORD_1 > tok
 
-AH=$(hawk -i `cat token` -p 'v8(9D1A>7n9J<' -H localhost -P /protected -O 80 -M GET -a sha256 -m header)
+AH=$(hawk -i `cat token` -p 'v8(9D1A>7n9J<' -H localhost -P /protectedxx -O 80 -M GET -a sha256 -m header)
 
 STATUS=`curl -s -H "$AH" http://localhost/protected -w "%{http_code}" -o /dev/null`;
 
@@ -11,6 +11,13 @@ if [ $STATUS -ne 401 ] ; then
 	echo "... Expected 401 but got $STATUS";
         cat tok;
 	echo "... $AH";
+	exit 1;
+fi
+
+
+if [ tail -1 /usr/local/nginx/logs/error.log | grep 'Invalid signature in Hawk' -ne 0 ] ; then
+	echo "... Expected error message not present in error log'
+	tail -1 /usr/local/nginx/logs/error.log
 	exit 1;
 fi
 
